"""leagues teams rosters

Revision ID: 0001
Revises:
Create Date: 2026-10-08 18:51:25.672922

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "leagues",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("platform_league_id", sa.String(), nullable=False),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("num_teams", sa.Integer(), nullable=False),
        sa.Column("lineup_slots", sa.JSON(), nullable=False),
        sa.Column("bench_slots", sa.Integer(), nullable=False),
        sa.Column("ir_slots", sa.Integer(), nullable=False),
        sa.Column("taxi_slots", sa.Integer(), nullable=False),
        sa.Column("scoring", sa.JSON(), nullable=False),
        sa.Column("unsupported_slots", sa.JSON(), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("league_id", sa.String(), nullable=False),
        sa.Column("platform_team_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("owner_name", sa.String(), nullable=True),
        sa.Column("is_me", sa.Boolean(), nullable=False),
        sa.Column("wins", sa.Integer(), nullable=False),
        sa.Column("losses", sa.Integer(), nullable=False),
        sa.Column("ties", sa.Integer(), nullable=False),
        sa.Column("points_for", sa.Double(), nullable=False),
        sa.Column("empty_lineup_slots", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["league_id"], ["leagues.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "roster_entries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("team_id", sa.String(), nullable=False),
        sa.Column("platform_player_id", sa.String(), nullable=False),
        sa.Column("player_key", sa.String(), nullable=True),
        sa.Column("match_method", sa.String(length=16), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("position", sa.String(length=8), nullable=True),
        sa.Column("slot_type", sa.String(length=8), nullable=False),
        sa.Column("lineup_slot", sa.String(length=16), nullable=True),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_roster_entries_player_key", "roster_entries", ["player_key"], unique=False)
    op.create_index(op.f("ix_roster_entries_team_id"), "roster_entries", ["team_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_roster_entries_team_id"), table_name="roster_entries")
    op.drop_index("ix_roster_entries_player_key", table_name="roster_entries")
    op.drop_table("roster_entries")
    op.drop_table("teams")
    op.drop_table("leagues")
    # ### end Alembic commands ###
